# 激活环境
source /data25/wuqin/miniforge3/etc/profile.d/mamba.sh
mamba activate qwen2_5vl
export PYTHONPATH=./

# 脚本用法

# CLIP案例
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/002_004_IMG_1786.jpg --labels "plant", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "table", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "two tables against the wall", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "display", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "two monitors on the wall", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "floor", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "ceiling", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "Om AI", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "car", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "person", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "traffic light", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "sidewalk", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/both.png --labels "cat", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000037862.jpg --labels "dog", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000037862.jpg --labels "The biggest white dog", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000120524.jpg --labels "The sheep beside the dog", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000555022.jpg --labels "Items on the TV.", "background"
python usage_examples/clip_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/test2.jpg --labels "The sofa in the middle.", "background"

# MetaCLIP2
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/002_004_IMG_1786.jpg --labels "绿植", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "桌子", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "靠墙的两张桌子", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "显示器", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "墙上的两个显示器", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "地板", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "天花板", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "OmAI", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "车辆", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "人", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "红绿灯", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "人行道", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/both.png --labels "猫", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000037862.jpg --labels "狗", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000037862.jpg --labels "最大的白色的狗", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000120524.jpg --labels "狗旁边的羊", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000555022.jpg --labels "电视机上的物品", "背景"
python usage_examples/metaclip2_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/test2.jpg --labels "中间的沙发", "背景"

# clip_surgery
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/002_004_IMG_1786.jpg --labels "plant"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "table"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "two tables against the wall"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "display"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "two monitors on the wall"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "floor"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "ceiling"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "Om AI"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "car"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "person"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "traffic light"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "sidewalk"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/both.png --labels "cat"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000037862.jpg --labels "dog"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000037862.jpg --labels "The biggest white dog"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000120524.jpg --labels "The sheep beside the dog"
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000555022.jpg --labels "Items on the TV."
python usage_examples/clip_surgery_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/test2.jpg --labels "The sofa in the middle."

# lseg
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/002_004_IMG_1786.jpg --labels "plant"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "table"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "two tables against the wall"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "display"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "two monitors on the wall"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "floor"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "ceiling"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/006_000_IMG_1794.jpg --labels "Om AI"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "car"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "person"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "traffic light"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/65113a4ee4b0499a6ee19c83.jpg --labels "sidewalk"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/both.png --labels "cat"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000037862.jpg --labels "dog"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000037862.jpg --labels "The biggest white dog"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000120524.jpg --labels "The sheep beside the dog"
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/COCO_train2014_000000555022.jpg --labels "Items on the TV."
python usage_examples/lseg_example.py --image-path /data25/wuqin/projects/pytorch-grad-cam/testset/test2.jpg --labels "The sofa in the middle."

